// Stores the selected rectangle for one persistent building generated by TestBuildingCreator.
using UnityEngine;

public sealed class TestBuildingLayout : MonoBehaviour
{
    [SerializeField] private Vector3Int anchorCell;
    [SerializeField] private Vector2Int size;

    public Vector3Int AnchorCell => anchorCell;
    public Vector2Int Size => size;

    public void Configure(Vector3Int newAnchorCell, Vector2Int newSize)
    {
        anchorCell = newAnchorCell;
        size = newSize;
    }
}
